### PR TITLE
NamespaceRegistration Name Prefix: better error msg

### PR DESCRIPTION
**Pull request by enrico-kaack-comp**
**What this PR does / why we need it**:
Improve error message if name of NamespaceRegistration does not start with the cu- prefix.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature user

```

### CODE REVIEW

**Review by achimweigel — CHANGES_REQUESTED** [review]
I guess you need to rebase your branch such that the tests are running

**Comment by reshnm** [comment]
I think you need to rebase again for the integration test to work. :-(

**Review by reshnm — APPROVED** [review]
/lgtm

**Review by robertgraeff — APPROVED** [review]

**Review by achimweigel — APPROVED** [review]
/lgtm

**Pull request merged**
